from enum import Enum


class HarmCategory(str, Enum):
    HARM_CATEGORY_UNSPECIFIED = "HARM_CATEGORY_UNSPECIFIED"
    HARM_CATEGORY_DEROGATORY = "HARM_CATEGORY_DEROGATORY"
    HARM_CATEGORY_TOXICITY = "HARM_CATEGORY_TOXICITY"
    HARM_CATEGORY_VIOLENCE = "HARM_CATEGORY_VIOLENCE"
    HARM_CATEGORY_SEXUAL = "HARM_CATEGORY_SEXUAL"
    HARM_CATEGORY_MEDICAL = "HARM_CATEGORY_MEDICAL"
    HARM_CATEGORY_DANGEROUS = "HARM_CATEGORY_DANGEROUS"
    HARM_CATEGORY_HARASSMENT = "HARM_CATEGORY_HARASSMENT"
    HARM_CATEGORY_HATE_SPEECH = "HARM_CATEGORY_HATE_SPEECH"
    HARM_CATEGORY_SEXUALLY_EXPLICIT = "HARM_CATEGORY_SEXUALLY_EXPLICIT"
    HARM_CATEGORY_DANGEROUS_CONTENT = "HARM_CATEGORY_DANGEROUS_CONTENT"
    HARM_CATEGORY_CIVIC_INTEGRITY = "HARM_CATEGORY_CIVIC_INTEGRITY"


class HarmBlockThreshold(str, Enum):
    HARM_BLOCK_THRESHOLD_UNSPECIFIED = "HARM_BLOCK_THRESHOLD_UNSPECIFIED"
    BLOCK_LOW_AND_ABOVE = "BLOCK_LOW_AND_ABOVE"
    BLOCK_MEDIUM_AND_ABOVE = "BLOCK_MEDIUM_AND_ABOVE"
    BLOCK_ONLY_HIGH = "BLOCK_ONLY_HIGH"
    BLOCK_NONE = "BLOCK_NONE"
    OFF = "OFF"


class FinishReason(str, Enum):
    FINISH_REASON_UNSPECIFIED = "FINISH_REASON_UNSPECIFIED"
    STOP = "STOP"
    MAX_TOKENS = "MAX_TOKENS"
    SAFETY = "SAFETY"
    RECITATION = "RECITATION"
    LANGUAGE = "LANGUAGE"
    OTHER = "OTHER"
    BLOCKLIST = "BLOCKLIST"
    PROHIBITED_CONTENT = "PROHIBITED_CONTENT"
    SPII = "SPII"
    MALFORMED_FUNCTION_CALL = "MALFORMED_FUNCTION_CALL"
    IMAGE_SAFETY = "IMAGE_SAFETY"
    UNEXPECTED_TOOL_CALL = "UNEXPECTED_TOOL_CALL"


class BlockReason(str, Enum):
    BLOCK_REASON_UNSPECIFIED = "BLOCK_REASON_UNSPECIFIED"
    SAFETY = "SAFETY"
    OTHER = "OTHER"
    BLOCKLIST = "BLOCKLIST"
    PROHIBITED_CONTENT = "PROHIBITED_CONTENT"
    IMAGE_SAFETY = "IMAGE_SAFETY"


class HarmProbability(str, Enum):
    HARM_PROBABILITY_UNSPECIFIED = "HARM_PROBABILITY_UNSPECIFIED"
    NEGLIGIBLE = "NEGLIGIBLE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class Language(str, Enum):
    LANGUAGE_UNSPECIFIED = "LANGUAGE_UNSPECIFIED"
    PYTHON = "PYTHON"


class Outcome(str, Enum):
    OUTCOME_UNSPECIFIED = "OUTCOME_UNSPECIFIED"
    OUTCOME_OK = "OUTCOME_OK"
    OUTCOME_FAILED = "OUTCOME_FAILED"
    OUTCOME_DEADLINE_EXCEEDED = "OUTCOME_DEADLINE_EXCEEDED"


class Type(str, Enum):
    TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED"
    STRING = "STRING"
    NUMBER = "NUMBER"
    INTEGER = "INTEGER"
    BOOLEAN = "BOOLEAN"
    ARRAY = "ARRAY"
    OBJECT = "OBJECT"
    NULL = "NULL"


class Behavior(str, Enum):
    BEHAVIOR_UNSPECIFIED = "UNSPECIFIED"
    BLOCKING = "BLOCKING"
    NON_BLOCKING = "NON_BLOCKING"


class FunctionCallingConfigMode(str, Enum):
    MODE_UNSPECIFIED = "MODE_UNSPECIFIED"
    AUTO = "AUTO"
    ANY = "ANY"
    NONE = "NONE"
    VALIDATED = "VALIDATED"


class Scheduling(str, Enum):
    SCHEDULING_UNSPECIFIED = "SCHEDULING_UNSPECIFIED"
    SILENT = "SILENT"
    WHEN_IDLE = "WHEN_IDLE"
    INTERRUPT = "INTERRUPT"


class MediaResolution(str, Enum):
    MEDIA_RESOLUTION_UNSPECIFIED = "MEDIA_RESOLUTION_UNSPECIFIED"
    MEDIA_RESOLUTION_LOW = "MEDIA_RESOLUTION_LOW"
    MEDIA_RESOLUTION_MEDIUM = "MEDIA_RESOLUTION_MEDIUM"
    MEDIA_RESOLUTION_HIGH = "MEDIA_RESOLUTION_HIGH"


class Modality(str, Enum):
    MODALITY_UNSPECIFIED = "MODALITY_UNSPECIFIED"
    TEXT = "TEXT"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    DOCUMENT = "DOCUMENT"


class Role(str, Enum):
    USER = "user"
    MODEL = "model"


class SchemaFormat(str, Enum):
    FLOAT = "float"
    DOUBLE = "double"
    INT32 = "int32"
    INT64 = "int64"
    ENUM = "enum"
    DATE_TIME = "date-time"


class DynamicRetrievalMode(str, Enum):
    MODE_UNSPECIFIED = "MODE_UNSPECIFIED"
    MODE_DYNAMIC = "MODE_DYNAMIC"


class UrlRetrievalStatus(str, Enum):
    URL_RETRIEVAL_STATUS_UNSPECIFIED = "URL_RETRIEVAL_STATUS_UNSPECIFIED"
    URL_RETRIEVAL_STATUS_SUCCESS = "URL_RETRIEVAL_STATUS_SUCCESS"
    URL_RETRIEVAL_STATUS_ERROR = "URL_RETRIEVAL_STATUS_ERROR"


class State(str, Enum):
    STATE_UNSPECIFIED = "STATE_UNSPECIFIED"
    PROCESSING = "PROCESSING"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"


class Source(str, Enum):
    SOURCE_UNSPECIFIED = "SOURCE_UNSPECIFIED"
    UPLOADED = "UPLOADED"
    GENERATED = "GENERATED"
    REGISTERED = "REGISTERED"
